# Generated by Django 5.0.6 on 2024-07-02 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molnix_id', models.IntegerField(blank=True, null=True)),
                ('alert_record_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('role_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('rotation', models.CharField(blank=True, max_length=255, null=True)),
                ('modality', models.CharField(blank=True, max_length=255, null=True)),
                ('language_required', models.CharField(blank=True, max_length=255, null=True)),
                ('molnix_status', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_status', models.CharField(blank=True, max_length=255, null=True)),
                ('opens', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('sectors', models.CharField(blank=True, max_length=255, null=True)),
                ('role_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('im_filter', models.BooleanField(default=False)),
                ('iso3', models.CharField(blank=True, max_length=255, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disaster_type_id', models.IntegerField(blank=True, null=True)),
                ('disaster_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disaster_go_id', models.IntegerField(blank=True, null=True)),
                ('ifrc_severity_level_display', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_id', models.IntegerField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
