# Generated by Django 5.0.6 on 2024-07-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_deployment_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='surge_alert',
            field=models.ForeignKey(db_column='alert_id', on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='app.alert'),
        ),
    ]
